#!/bin/sh

FAC_DIR="Facultad"

alias ls="ls --color=auto"
alias ll="ls -lah"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias sn="sudo shutdown now"
alias xclip="xclip -sel clipb"
alias v="vim"
alias ccat="highlight --out-format=ansi"
alias fzf="fzf --reverse"
alias tk="tmux kill-session"
alias fdef="sdcv -u \"Dictionnaire de l’Académie française, 8ème édition (1935)\""
alias edef="sdcv -u \"English explanatory dictionary (main)\""
alias wget="wget --read-timeout=5"
alias youtube-dl="/usr/local/bin/youtube-dl -x --audio-format mp3"
alias ginit="eval \"$(ssh-agent -s)\""
alias ndate="date +"%d-%m-%Y""
alias mdtoday="mkdir $(date +"%d-%m-%Y")"
alias bashrst=". ~/.bashrc"
alias facultadsh=". ~/$FAC_DIR/facultad.sh"
alias rnet="sudo systemctl restart NetworkManager"
alias ew="cd ~/Academy/writing/"

if [ $(lsb_release -is) = "Debian" ]; then
  alias au="sudo apt update"
  alias aU="sudo apt upgrade"
  alias ai="sudo apt install"
fi

fcd () { cd "$(find $1 -type d | fzf)"; }

hf () { bash -c "$(history | fzf --tac | awk '{ for (i = 2; i < NF; i++) printf $i " "; print $NF  }')"; }

tn () { 
  if [ ! -z "$1"  ]; then 
    tmux new-session -A -s $1 
  else
    tmux
  fi
}

fcp () { cp "$(find $1 -type f | fzf)" .;  }

mcd () { mkdir -p "$1" && cd "$1"; }

fv () { vim $(find $1 -type f | fzf);  }

mt () { cd $(mktemp -d); }

zathura () { 
  nohup zathura $1 >/dev/null 2>/dev/null &
}

zat () {
  local pdf="$(find . -name "*.pdf" -not -path "*/\.*" | fzf)"
  if [ ! -z $pdf ]; then
    zathura $pdf
  fi
}

chgname () {
  if [ ! -z "$1" ]; then
    new_name=$(echo $1 | tr 'A-Z' 'a-z' | tr -d '-' | sed -E 's/\s+/-/g')

    mv "$1" "$new_name"
  fi
}

wtoday () {
  vim $(date +"%d-%m-%Y").txt
}

vdream () {
  vim -p sueno.txt asociacion.txt extender.txt
}
