#!/bin/sh

# set vi mode
set -o vi

# Variables
export EDITOR=vim

# Man/Less
export LESS_TERMCAP_mb=$'\e[0;4;34m'
export LESS_TERMCAP_md=$'\e[0;4;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[0;32m'

export HISTSIZE=1000
export HISTFILESIZE=2000

shopt -s autocd # cd just typing dir name

